# Generated by Django 6.0.3 on 2026-04-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_phone', models.CharField(max_length=15, unique=True)),
                ('emp_department', models.CharField(max_length=50)),
            ],
        ),
    ]
